# action.yml
name: 'Automatic release prosedure'
description: 'Tagging with a daily versions preference'
inputs:
  name: # id of input
    description: 'App name'
    required: true
  environment:
    description: 'A stage eg. dev, staging, production..'
    required: true

runs:
  using: 'node16'
  main: 'index.js'
