# action.yml
name: 'Automatic release prosedure'
description: 'Tagging with a daily versions preference'
inputs:
  name: # id of input
    description: 'App name'
    required: true
  environment:
    description: 'A stage eg. dev, staging, production..'
    required: true
  githubToken:
    description: 'Github action token'
    required: false
  githubSHA:
    description: 'Github commit hash'
    required: false

runs:
  using: 'node16'
  main: 'index.js'
