on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test automatic versioning
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Test action
        id: test
        uses: ./
        with:
          name: automatic-release-action
          environment: dev
          githubToken: ${{ secrets.GITHUB_TOKEN }}
